export const LOAD_IMAGE = 'LOAD_IMAGE';
export const LOAD_IMAGE_SUCCESS = 'LOAD_IMAGE_SUCCESS';
export const UPDATE_PIXEL_SIZE = 'UPDATE_PIXEL_SIZE';
export const UPDATE_CONTRAST = 'UPDATE_CONTRAST';
export const UPDATE_BRIGHTNESS = 'UPDATE_BRIGHTNESS';
export const UPDATE_SATURATION = 'UPDATE_SATURATION';
export const UPDATE_COLOR_COUNT = 'UPDATE_COLOR_COUNT';
export const ENABLE_PAINT = 'ENABLE_PAINT';